viewer: Try to import GdkX11 as it will be needed to embed window on X11
Fixing:
  AttributeError: 'gtk.gdk.X11Window' object has no attribute 'get_xid'