elements: Fix selection of groups
And add a test where we were getting:

  AttributeError: 'NoneType' object has no attribute 'get_children'

because of that.

Reviewed-by: Alex Băluț <alexandru.balut@gmail.com>
Differential Revision: https://phabricator.freedesktop.org/D626