timeline: fix missing import
fix following exception:

Traceback (most recent call last):
  File "/usr/lib/pitivi/python/pitivi/timeline/timeline.py", line 1197,
in _dragLeaveCb
    GLib.timeout_add(75, self._dragCleanUp, context)
NameError: global name 'GLib' is not defined