medialibrary: Make sure the asset is prepared before being used
Should fix tests.test_media_library.TestMediaLibrary.test_delete_proxy which
fails sometimes with:

> ...
>   File "/root/pitivi/pitivi/medialibrary.py", line 357, in __setState
>     elif asset.proxying_error:
> 'UriClipAsset' object has no attribute 'proxying_error'